spring:
  application:
    name: technical-test-api
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27000/webflux_db

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data: TRACE
        web.filter.CommonsRequestLoggingFilter: DEBUG